# Generated by Django 4.2.6 on 2023-10-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_second_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
