# Generated by Django 4.2.6 on 2023-10-16 03:21

from django.db import migrations, models
import django.db.models.deletion
import milky_way.utils
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
            bases=(milky_way.utils.CustomStr, models.Model),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Фамилия Имя Отчество')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telegram', models.CharField(blank=True, help_text='В поле указывается username аккаунта (не ID и не телефон)', max_length=255, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
            bases=(milky_way.utils.CustomStr, models.Model),
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа плательщика')),
            ],
            options={
                'verbose_name': 'Плательщик',
                'verbose_name_plural': 'Плательщики',
            },
            bases=(milky_way.utils.CustomStr, models.Model),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название офиса')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='logistic.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
            },
            bases=(milky_way.utils.CustomStr, models.Model),
        ),
    ]
