# Generated by Django 4.2.6 on 2023-10-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_cashcollection_parcel_shipstatus_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='from_office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parcels_from_office', to='logistic.office', verbose_name='Пункт отправления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='to_office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parcels_to_office', to='logistic.office', verbose_name='Пункт доставки'),
            preserve_default=False,
        ),
    ]
