# Generated by Django 4.2.6 on 2024-02-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_alter_transaction_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ['-id'], 'verbose_name': 'Посылка', 'verbose_name_plural': 'Посылки'},
        ),
    ]
