# Generated by Django 4.2.6 on 2024-02-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0008_alter_parcel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='code',
            field=models.CharField(default=1234, max_length=4),
            preserve_default=False,
        ),
    ]
